# Generated by Django 3.2.5 on 2021-07-13 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicoprestado',
            old_name='empresa_prestadadora',
            new_name='empresa_prestadora',
        ),
    ]
