# Generated by Django 3.2.5 on 2021-07-14 01:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_empresa_prestadadora_servicoprestado_empresa_prestadora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='servicoprestado',
            name='data',
            field=models.DateField(default=datetime.date(2021, 7, 14)),
        ),
        migrations.AlterField(
            model_name='servicoprestado',
            name='empresa_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos_recebido', to='core.empresa'),
        ),
        migrations.AlterField(
            model_name='servicoprestado',
            name='empresa_prestadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='servicos_prestado', to='core.empresa'),
        ),
    ]
