# Generated by Django 3.2.5 on 2021-07-15 01:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210713_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicoprestado',
            name='data',
            field=models.DateField(default=datetime.date(2021, 7, 15)),
        ),
    ]
