# Generated by Django 3.2.5 on 2021-07-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_servicoprestado_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='descricao',
        ),
        migrations.AddField(
            model_name='servicoprestado',
            name='descricao',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
