# Generated by Django 3.2.5 on 2021-07-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210714_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='valor',
        ),
        migrations.AddField(
            model_name='servicoprestado',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
